### PR TITLE
fix bug for compatible with webkit-3.0

### PR DESCRIPTION
**Pull request by xiaolou86**

### CODE REVIEW

**Comment by CendioOssman** [comment]
The principle is sound, but we also grab `contextmenu` so we need to check which event type it is.

**Comment by samhed** [comment]
How old is webkit-3.0 and where do you use it? I can't find any information about webkit versions. The only browser that uses webkit now-a-days is safari right?

**Comment by xiaolou86** [comment]
@CendioOssman Yes. It should be more careful.
@samhed  Its api docs are here: https://lazka.github.io/pgi-docs/#WebKit-3.0

**Comment by DirectXMan12** [comment]
what version of webkit are we on for safari?  I'm not sure how much I want to support some super-old version that's not relevant for any real browsers.

**Comment by CendioOssman** [comment]
I'd say somewhere around version 10 of Safari, which wikipedia claims is webkit 602. Don't know how that relates to webkit-3 versions. I would assume that Safari 10 supports event constructors though, so I'd say webkit-3 is older.

**Comment by DirectXMan12** [comment]
Agreed, feel free to close

**Comment by xiaolou86** [comment]
Sorry to replay so late.

**Pull request closed without merging**
