### PR TITLE
Add translation in zh_CN

### PR DESCRIPTION
**Pull request by ghostplant**
Add translation in zh_CN.

Signed-off-by: CUI Wei <ghostplant@qq.com>

### CODE REVIEW

**Comment by samhed** [comment]
Thank you!

I'll update po/Makefile as well

**Comment by samhed** [comment]
> I'll update po/Makefile as well

nvm, you already did that :)

**Comment by ghostplant** [comment]
yes, but still need po2js to generate a js file which is not done yet~

**Comment by samhed** [comment]
Yes, that will be done before the next release

**Comment by ghostplant** [comment]
sounds good~

**Pull request merged**
