### PR TITLE
QEMU Pointer Motion Change Pseudo-encoding

### PR DESCRIPTION
**Pull request by Ekstazi**
From [community docs](https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#777qemu-pointer-motion-change-pseudo-encoding):

> ### 7.7.7   QEMU Pointer Motion Change Pseudo-encoding
> A client that supports this encoding declares that is able to send pointer motion events either as absolute coordinates, or relative deltas. The server can switch between different pointer motion modes by sending a rectangle with this encoding. If the x-position in the update is 1, the server is requesting absolute coordinates, which is the RFB protocol default when this encoding is not supported. If the x-position in the update is 0, the server is requesting relative deltas.
> 
> When relative delta mode is active, the semantics of the PointerEvent message are changed. The x-position and y-position fields are to be treated as S16 quantities, denoting the delta from the last position. A client can compute the signed deltas with the logic:
> 
> `uint16 dx = x + 0x7FFF - last_x`
> `uint16 dy = y + 0x7FFF - last_y`
> If the client needs to send an updated button-mask without any associated motion, it should use the value 0x7FFF in the x-position and y-position fields of the PointerEvent
> 
> Servers are advised to implement this pseudo-encoding if the virtual desktop is associated a input device that expects relative coordinates, for example, a virtual machine with a PS/2 mouse. Prior to this extension, a server with such a input device would have to perform the absolute to relative delta conversion itself. This can result in the client pointer hitting an "invisible wall".
> 
> Clients are advised that when generating events in relative pointer mode, they should grab and hide the local pointer. When the local pointer hits any edge of the client window, it should be warped back by 100 pixels. This ensures that continued movement of the user's input device will continue to generate relative deltas and thus avoid the "invisible wall" problem.

I implemented it.  But i doesn't have much knowledge to make autotests for it (I'm backender). But i tested it manually. Please verify and merge to upstream.

### CODE REVIEW

**Comment by samhed** [comment]
Thanks for the contribution. We'll try to find some time to look at this soon, but I'm quite swamped in the upcoming days.

**Comment by Ekstazi** [comment]
Ok, thx!

**Comment by CendioOssman** [comment]
Hmm... How can we test this? This extension doesn't seem to be possible to implement correctly in noVNC as the browser will not let us grab and manipulate the pointer.

**Comment by Ekstazi** [comment]
@CendioOssman 
> Hmm... How can we test this? 

You can connect to windows installed in qemu with spice enabled and tablet mode disabled. Then try to use mouse without my patch and with. Without patch pointer is crazy because user can't position it(motion speed is inadequate). With this patch mouse pointer moved smoothly so you can position it. 

> as the browser will not let us grab and manipulate the pointer.

I also created some kind of synchronization areas near the edges of Display. This allow to synchronize mouse position with remote position. And solve this problem partially.

You can look deeper into my commit and saw my comments about this.

**Comment by CendioOssman** [comment]
> You can connect to windows installed in qemu with spice tablet mode disabled and without spice/virtio drivers. Then try to use mouse without my patch and with. Without patch pointer is crazy because user can't position it(motion speed is inadequate). With this patch mouse pointer moved smoothly so you can position it.

I'm afraid I don't have easy access to a QEMU machine with Windows on it. Can this be tested with a free OS? I have a CentOS 7 machine here, but I'm not getting any sane behaviour.

> I also created some kind of synchronization areas near the edges of Display. This allow to synchronize mouse position with remote position. And solve this problem partially.
> 
> You can look deeper into my commit and saw my comments about it.

I did, and it looked very odd to me. That's why I wanted to test things. I fail to see how exaggerating the mouse movement can reliably work.

**Comment by CendioOssman** [comment]
Hmm... It looks like there is actually some support for this scenario in the browsers:

https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API

Have you looked at that and see how it works here?

**Comment by Ekstazi** [comment]
> I'm afraid I don't have easy access to a QEMU machine with Windows on it. Can this be tested with a free OS? I have a CentOS 7 machine here, but I'm not getting any sane behaviour.

As i know linux kernel include vmmouse driver which enable absolute pointing method. Your can test this patch only with windows or not *nix based systems. 

> Hmm... It looks like there is actually some support for this scenario in the browsers:
> https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API
> Have you looked at that and see how it works here?

Hm, i'll take look at it. Thx for the link.

**Comment by Ekstazi** [comment]
> Hmm... It looks like there is actually some support for this scenario in the browsers:
> https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API
> Have you looked at that and see how it works here?

As i understand this is exactly that needed. I'll make some experiments at weekend. After that i'll share results.

**Comment by CendioOssman** [comment]
> As i know linux kernel include vmmouse driver which enable absolute pointing method. Your can test this patch only with windows or not *nix based systems.

vmmouse is for VMware. If you remove the tablet device from QEMU, then you get an emulated PS/2 device handled by evdev on Linux. I.e. exactly the same as real hardware.

So there is something else missing in getting this working reliable. Or I simply haven't found a client that properly supports relative mouse movement. I thought that vinagre did...

**Comment by Ekstazi** [comment]
> vmmouse is for VMware. If you remove the tablet device from QEMU, then you get an emulated PS/2 device handled by evdev on Linux. I.e. exactly the same as real hardware.

This driver also works for qemu. I tested it on windows. And it enables absolute positioning mode without tablet device.
https://github.com/qemu/qemu/blob/f2cfa1229e539ee1bb1822912075cf25538ad6b9/hw/i386/pc.c#L2036

As you can see qemu emulates vmware mouse. Probably you can blacklist vmmouse driver in linux guest and then relative pointer will be enabled.

Why you can't test it on windows vm ?

**Comment by Ekstazi** [comment]
Also i think you can modify my code to see if absolute or relative pointer mode used.

**Comment by Ekstazi** [comment]
If you can't find a guest with relative pointing mode I can temporary share windows guest with you. If you contact me by email.

**Comment by samhed** [comment]
@Ekstazi I sent you an email

**Comment by samhed** [comment]
We couldn't find a way to test this, and I wrote an email regarding sharing that windows guest of yours. If we are going to get this merged we need to be able to do some testing ourselves.

**Comment by Ekstazi** [comment]
Hi, @samhed  I received your email. I'll provide test sandbox for you on this week.

**Comment by CendioOssman** [comment]
And to reiterate, I suspect this won't be complete without the pointer lock stuff is in place.

Did you have a chance to test using that?

**Comment by samhed** [comment]
No response.

**Pull request closed without merging**
