### PR TITLE
Allow users to specify CERT, WEB and PORT etc, through env variable

### PR DESCRIPTION
**Pull request by Neilpang**
Allow users set CERT etc by env variable.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
What's the use case here?  If you're doing this in production, you probably shouldn't be using launch.js anyway, and I'm not entirely certain as to why you can't just pass the flag.

**Comment by Neilpang** [comment]
@DirectXMan12 

For example, if I run noVNC in docker,  I have to  set those values throw env variable.

**Comment by Neilpang** [comment]
@DirectXMan12 
Here is my use case: 
https://github.com/Neilpang/novncbox#4-access-via-ssl

I need to specify `ssl_only` and cert file by the env variable.

**Comment by CendioOssman** [comment]
Just modify `startup.sh` there to do what you need. It can easily add arguments based on environment.

**Pull request closed without merging**
