### PR TITLE
Limit MouseMove Messages to once per 100mS

### PR DESCRIPTION
**Pull request by uklatt**
Perhaps this should be adjustable from the settings page...

### CODE REVIEW

**Comment by samhed** [comment]
Why do you want this? What problem are you seeing?

**Comment by CendioOssman** [comment]
We saw issues with this on TigerVNC as well:

https://github.com/TigerVNC/tigervnc/commit/157f54202ee570b1f00e8f0e5db660750b548c3c

The timeout chosen there was 60 Hz/17 ms as that seemed like a safe bet. 100 ms might be noticeable.

You also have to have a timeout for a final update, or the cursor position might not be properly updated.

**Comment by uklatt** [comment]
My "problem" was a nearly unusable mouse because many move events add a great lag.
UltraVNC client can limit this, novnc cant.
My patch solved this for me.
This should be adjustable in thesettings...

Uwe

**Comment by CendioOssman** [comment]
I don't think this needs to be configurable as long as we put a decent value on it.

So please change to 17 ms, and add handling for a final update once the cursor stops moving. After that we can merge this.

The variables could also use some more specific naming so it's obvious what they are used for.

**Comment by uklatt** [comment]
Closed because new version created

**Comment by samhed** [comment]
For future reference, you can force-push to an existing branch in order to update an existing PR.

**Pull request closed without merging**
