### PR TITLE
Refactor hasScrollbarGutter into a function

### PR DESCRIPTION
**Pull request by Ron-Lavi**
the code to determine hasScrollbarGutter can run while the document.body is not loaded yet. setting it as a function will trigger it when the actual UI is loaded, and document.body should exist.

### CODE REVIEW

**Comment by Ron-Lavi** [comment]
@samhed could you take a look? :)

**Comment by CendioOssman** [comment]
I'm not sure about this change, as this might have a lot of overhead (since it does layout stuff).

In which scenario have you seen this running early enough to crash?

**Comment by Ron-Lavi** [comment]
Hey @CendioOssman! when we import the library into our project, we always see the error in the browser console,
that `document.body` is undefined.
I think it's because we load the scripts in the page `head` and immediately the scrollbar test here is starting to run while the body wasn't finished to load yet.

**Comment by CendioOssman** [comment]
We do the same here, so there seems to be something more to it.

Are you mangling the code in some way? E.g. converting it from modules to classical JavaScript? That would affect how the files are loaded.

**Comment by Ron-Lavi** [comment]
yeah, I think that's what happens,
basically due to our JS architecture with plugins, IIRC we first bundle them together in:
https://github.com/theforeman/foreman-js/blob/master/packages/vendor-core/lib/modules.js#L117

and then using it in:
https://github.com/theforeman/foreman/blob/develop/webpack/assets/javascripts/bundle_novnc.js#L4

which is later used as vanilla JS in https://github.com/theforeman/foreman/blob/develop/app/views/hosts/console/vnc.html.erb

**Comment by Ron-Lavi** [comment]
@CendioOssman rebased :)

**Comment by Ron-Lavi** [comment]
Closing as it doesn't seem to be resolved here,
and on our side we indeed solved it by passing the script to the html body.

**Pull request closed without merging**
