### PR TITLE
Remove generated HTML by Cursor when it detaches

### LINKED ISSUE #1358: Multiple pointers on the screen on iPad
**Describe the bug**
Running noVNC on an iPad for a while I end up with a bunch of mouse pointers all over the screen:

```html
<canvas style="position: fixed; z-index: 65535; pointer-events: none; left: 740px; top: 280px;" width="16" height="16"></canvas>
<canvas style="position: fixed; z-index: 65535; pointer-events: none; left: 446px; top: 521px;" width="16" height="16"></canvas><canvas style="position: fixed; z-index: 65535; pointer-events: none; visibility: hidden;" width="0" height="0"></canvas>
<canvas style="position: fixed; z-index: 65535; pointer-events: none; visibility: hidden;" width="0" height="0"></canvas>
<canvas style="position: fixed; z-index: 65535; pointer-events: none; left: 765px; top: 461px;" width="10" height="16"></canvas>
<canvas style="position: fixed; z-index: 65535; pointer-events: none; visibility: hidden;" width="0" height="0"></canvas><canvas style="position: fixed; z-index: 65535; pointer-events: none; visibility: hidden;" width="0" height="0"></canvas>
```

It seems to have to do with fast touches or multitouches.

Should the mouse pointer show at all when using touch devices?
Can it be hidden?

**To Reproduce**
I haven't tested in the noVNC UI since I'm embedding the library in my own UI.

**Expected behavior**
Only one pointer is visible at a time.

**Screenshots**

**Client (please complete the following information):**
 - OS: iOS
 - Browser: safari
 - Browser version: latest

**Server (please complete the following information):**
 - noVNC version: 1.1.0
 - VNC server: TigerVNC
 - WebSocket proxy: websockify

### PR DESCRIPTION
**Pull request by juanjoDiaz**
Fixes #1358 

I still think that a separate `connect` method to make `Rfb` instances reusable is the way to go.
But this is an improvement nevertheless.

### CODE REVIEW

**Comment by juanjoDiaz** [comment]
The tests seem to be failing on IE with error like `Invalid descriptor for property 'navigator'` and `Invalid descriptor for property 'localStorage'` which doesn't seem to be related to my commit. Any idea?

**Comment by CendioOssman** [comment]
This fix looks correct, thanks for finding the bug. Not sure why IE is upset. I agree it looks unrelated. I'll see if I can find what has gone wrong.

**Comment by CendioOssman** [comment]
Ah, there is a new version of mocha out. I can reproduce it locally here as well after an update. I'll see if I can figure out what changed and fix it.

**Comment by juanjoDiaz** [comment]
Adding a `package-lock.json` to the repo would solve the issue and prevent things like this in the future. 🙂

**Comment by CendioOssman** [comment]
That merely delays problems and doesn't really solve them. So we purposefully avoid such things.

**Pull request merged**
