### PR TITLE
Update German Translation 

### PR DESCRIPTION
**Pull request by jannesblobel**
Hi, 

Changes

- added an inlang.config.js file to the root of the repo
- updated and fix German translations

I saw your german translation was broken. To make it easier for me to contribute to your translation, I added the tool [inlang/inlang](https://github.com/inlang/inlang). I am opening this  PR as a draft to discuss the tool. Maintainers or contributors would have no overhead as inlang is built on git. No accounts (login with GitHub), no sync, and no pipelines are required. Contributions open a PR. 

Would an UI over the translations in this repo be of benefit to the noVNC community?

You can try it out on my fork and post your feedback under this draft. 
https://inlang.com/editor/github.com/jannesblobel/noVNC

Please keep in mind that you can translate any language in this project; my screen capture has the wrong settings  :( 

 The PR is theoretically ready for review
 
 
https://user-images.githubusercontent.com/72493222/215565696-e53aad4c-478d-4d2f-93a4-d7cc19306ab0.mp4

### CODE REVIEW

**Comment by jannesblobel** [comment]
Note: 
I saw a lot of translations that needed to be improved in other languages. Maybe you know some people and can ask for help :)

**Comment by CendioOssman** [comment]
We prefer to stay agnostic when it comes to which tool people use for translations. I don't think the tooling is the bottleneck, but rather getting people interested in contributing. We usually point to poedit, which is easy enough to install and use.

As such, I'd rather not add more things to maintain to the project.

You are welcome to split out the fixes you want to add for the German translation, though, and we can have a look at that.

**Comment by samuelstroschein** [comment]
@CendioOssman 

We want to help getting translation contributions for OSS projects. Would you, or someone on your team, be interested in joining a Discord channel with other maintainers to bounce around ideas? 
 
CleanShot 2023-02-02 at 14 34 38@2x

One thing we do already is showing projects that translators can contribute to on inlang.com, but we can surely do more to help OSS projects becoming more accessible by getting more translation contributions.

**Comment by CendioOssman** [comment]
I'm afraid I'm a bit too swamped at the moment. Perhaps at a later time when things are more calm.

**Pull request closed without merging**
