### PR TITLE
Update German translation

### PR DESCRIPTION
**Pull request by lxp**

### CODE REVIEW

**Comment by DirectXMan12** [comment]
Thanks for the translations!  From a code perspective, looks good (can't really comment from a german perspective, as I don't speak it).  I'll merge this after we get the module situation worked out in #774.  Thanks!

**Comment by samhed** [comment]
@lxp Could you rebase this to resolve the conflicts?

**Comment by samhed** [comment]
I fixed it, committed in 8a0cbd742b2a1c0ce2d827341163afb321558de5.

For future reference, no need to generate a new .pot file. And please don't modify the .js files directly, as you did with el.js, they are generated by make -C po update-js.

**Comment by samhed** [comment]
Anyway, thanks a lot for the translations!

**Pull request closed without merging**
