### PR TITLE
Change copyright header

### LINKED ISSUE #674: Copyright format at the top of files
As brought up by @DirectXMan12:

Currently we have a list at the top of each file listing contributors each on a separate line. These lists are currently quite incomplete and this style won't work well as the lists grow.

Suggestions? Thoughts @kanaka?

### PR DESCRIPTION
**Pull request by DirectXMan12**
This updates the copyright header to say "The noVNC Authors".  People
who previously had copyright listings are now under the AUTHORS file.

Closes #674

### CODE REVIEW

**Comment by DirectXMan12** [comment]
cc @kanaka @CendioOssman @kanaka

**Comment by kanaka** [comment]
lgtm

**Comment by CendioOssman** [comment]
I think we should have proper copyright names (including company name) in AUTHORS rather than Github usernames. But otherwise it looks fine to me.

**Comment by DirectXMan12** [comment]
I figured the github handles provides easy attribution independent of whether or not someone is at a particular company, and provides an easy way to track someone's current information down on GitHub.  We can always do follow-ups if you want your info listed in a different way.

**Comment by CendioOssman** [comment]
I don't like tying things that intimately to github. Hosting services come and go. I don't mind it as an addition as in your latest suggestion though.

A copyright notice also has legal implications, so including the company is important as it is they that hold (partly or fully) the copyright.

I would like the form used before, i.e. "Pierre Ossman for Cendio AB". I would also be fine with "Pierre Ossman for Cendio AB (@CendioOssman)".

**Comment by samhed** [comment]
I'd prefer:

> Samuel Mannehed for Cendio AB (@samhed)

**Comment by DirectXMan12** [comment]
ack, I'll fix that up.

**Comment by DirectXMan12** [comment]
That look better?

**Comment by samhed** [comment]
Looks good to me

**Comment by CendioOssman** [comment]
Looks good. I just noticed the URL in LICENSE.txt though. I think it is better if it is a local reference. Might be an old copy of noVNC, or they might not have internet. (or github might be gone)

Otherwise :+1:

**Pull request merged**
