### PR TITLE
fix chinese garbled code

### PR DESCRIPTION
**Pull request by gongym12138**
change clipboardPasteFrom unicode encode

### CODE REVIEW

**Comment by CendioOssman** [comment]
I'm afraid we cannot accept this code as it would violate the VNC protocol specification. Which server are you using this with?

**Comment by gongym12138** [comment]
> I'm afraid we cannot accept this code as it would violate the VNC protocol specification. Which server are you using this with?

**Comment by gongym12138** [comment]
> I'm afraid we cannot accept this code as it would violate the VNC protocol specification. Which server are you using this with?

I think it's also a server problem 

use https://www.tightvnc.com/download.php vncserver

**Comment by gongym12138** [comment]
> 比如说，你这个修改是修复没有VNC剪切板无法复制中文的问题么？
> 你最终有没有解决剪切板中文乱码问题？如果解决了，能否分享一下你的解决方案么？

我提交的代码就是修复了这个问题

**Pull request closed without merging**
