### PR TITLE
Move browser checks to browser.js

### PR DESCRIPTION
**Pull request by juanjoDiaz**
Just move all the duplicate `isMac`, `isWindow`, etc. to `browser.js`

### CODE REVIEW

**Comment by juanjoDiaz** [comment]
Any ETA for that?
I have more PRs for the eslint stuff sort of waiting for this to avoid conflicts.

**Comment by CendioOssman** [comment]
> Any ETA for that?
> I have more PRs for the eslint stuff sort of waiting for this to avoid conflicts.

I was hoping to get the beta out this week, but we probably want to let that be tested for a while before doing the final version. So it could be a while.

Perhaps it's better if you just use #1005 and put each suggestion as a separate commit rather than a separate PR? That way everything can be reviewed and done without having to wait for partial merges.

**Comment by DirectXMan12** [comment]
I've been gradually merging stuff that's not majorly impactful.  This is relatively minor, so it might be fine to merge pre-1.0, especially with the plan to do a beta.

**Comment by juanjoDiaz** [comment]
That would be great :)

**Comment by DirectXMan12** [comment]
@CendioOssman @samhed any objections to just merging this now?

**Comment by samhed** [comment]
works for me

**Comment by CendioOssman** [comment]
Yeah, this isn't too scary. So go ahead.

**Pull request merged**
