### PR TITLE
Adding disconnect_message Confirmation dialog

### PR DESCRIPTION
**Pull request by yatru**
When parameter disconnect_message is set, it will show a message to confirm the disconnection being its value the text on the confirm dialog.

This is related to the issue #1502 "two-step 'disconnect' option with custom message #1502"

### CODE REVIEW

**Comment by CendioOssman** [comment]
I would prefer if we start a bit more restrictive and have our own message. That way we can have it enabled by default, and we can make sure it is properly translated.

**Comment by yatru** [comment]
if that the case, we can reuse the "Disconnect" string that is already translated and add a question mark

` if (WebUtil.getConfigVar('disconnect_message', false) && confirm(_("Disconnect") + " ?") == false ) {
            return;
 }`

What do you think about it ?

**Comment by samhed** [comment]
Seeing as question marks work differently in different languages (for example spanish) we would need a different string anyway. No need to reuse something existing.

I suggest "Are you sure you want to disconnect?"

**Review by samhed — COMMENTED** [review]
It would be nice if we could have a "Don't show this again" checkbox. For that we would probably have to create our own dialog for this question instead of using `window.confirm()`. An alternative would be to have it in the settings somewhere.

Either way we would need to save a new setting for it.

**Comment by yatru** [comment]
I have the code for the custom dialog, I will upload it

**Comment by CendioOssman** [comment]
Have you been able to have a look at this, @yatru?

**Comment by CendioOssman** [comment]
No response. Closing.

**Pull request closed without merging**
