### PR TITLE
zrle and zywrle support

### PR DESCRIPTION
**Pull request by Ekstazi**
Support for ZRLE encoding
https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#zrle-encoding

I didn't benchmark it. But as my opinion it slightly slower than tight.

### CODE REVIEW

**Comment by Ekstazi** [comment]
zywrle support added

**Comment by Ekstazi** [comment]
I found some issue with qemu: pixel bytes are in inverse order. I don't know if it is qemu bug or it is standard order. Can anyone test it with realvnc/ultravnc server ?

**Comment by Ekstazi** [comment]
> I found some issue with qemu: pixel bytes are in inverse order. I don't know if it is qemu bug or it is standard behavior.

I did some research and found that novnc uses rgb le pixel format. This is similar to bgr be. Both hextile and raw encodings use convertion to rgb before display to canvas ?

Why bgr is the default pixel format ? May be we can switch it by default to rgb and avoid redundant loops/calculations ?

**Comment by CendioOssman** [comment]
Thanks for this PR. At first glance it looks very nice. I'll try to get some testing done soon.

I don't see any handling of ZYWRLE though. It is not the same thing as ZRLE.

> Why BGR888 is the default pixel format ? May be we can switch it by default to RGB888 BE and avoid redundant loops/calculations ?

Not sure, but I've also noticed that it seems a bit inefficient. @kanaka, do you remember why it was done this way?

**Comment by Ekstazi** [comment]
> I don't see any handling of ZYWRLE though. It is not the same thing as ZRLE.
As i can see in ultravnc implementation it is the same thing https://github.com/veyon/ultravnc/blob/b1be045bd39e8e335368bbcf8c4587e4c80aa338/rfb/zrleDecode.h#L235

I did some tests with qemu and didn't find any problems. But i can make additionals research for zywrle in future.

**Comment by Ekstazi** [comment]
> I did some tests with qemu and didn't find any problems. But i can make additionals research for zywrle in future.

I was wrong about ZYWRLE. It's different only for raw subencoding (0). I'll try to fix it soon.

**Comment by samhed** [comment]
I get the impression that you will do more work on this PR before we should consider it complete? Correct me if I'm wrong.
I've added the 'Work in Progress' label for now.

**Comment by Ekstazi** [comment]
yes, some improvements needed fir zywrle. but zrle fully completed

**Comment by samhed** [comment]
Any update on this?

**Comment by Ekstazi** [comment]
Still in progress. Need to split this PR into 3 new:
1. BE color scheme
2. ZRLE support
3. ZYWRLE support
Each will depend from previous....

чт, 2 янв. 2020 г., 15:21 Samuel Mannehed <notifications@github.com>:

**Comment by samhed** [comment]
Ok sounds good. We'll take one step at a time.

**Comment by AchuthSankar** [comment]
hey, could you tell me when this feature will be released ?

**Comment by CendioOssman** [comment]
Unfortunately it seems this PR has stalled. @Ekstazi , are you still working on this?

**Comment by Ekstazi** [comment]
Yes, I'm still working on this.

ср, 15 апр. 2020 г., 17:49 Pierre Ossman (Work account) <
notifications@github.com>:

**Comment by CendioOssman** [comment]
Any progress? :)

**Comment by samhed** [comment]
ping @Ekstazi

**Comment by CendioOssman** [comment]
Unfortunately this PR seems to be dead. :/
Closing.

**Comment by Neustradamus** [comment]
Replaced by:
- https://github.com/novnc/noVNC/pull/1587
- https://github.com/novnc/noVNC/pull/1589

Linked to:
- https://github.com/novnc/noVNC/issues/25
- https://github.com/novnc/noVNC/issues/545

**Comment by Neustradamus** [comment]
Note: Zywrle is not supported by noVNC.

**Pull request closed without merging**
