### PR TITLE
Added support for ZRLE encoding

### PR DESCRIPTION
**Pull request by pauldumais**
Added support for ZRLE encoding, work mostly based on work done by #1283, just had to fix up the ZRLE palette tile decoding.  Also used the same fix to the inflator that #1587 did as well.  Tested against TightVNC Server on Windows and iDRAC VNC server.

### CODE REVIEW

**Comment by rosmo** [comment]
Wow, this is really weird. @pauldumais I think you took a few notes from my PR (`allowIncomplete` for the inflator)? I think while this PR might be more straightforward, mine probably uses quite a bit less memory (I was testing on PC with 4k screen and the compressed data was around 4MB in size which decompressed is probably a lot more - I implemented a buffer system to reduce the memory usage. I'm also looking at the palette RLE decompression in this - I'm not sure if it supports padding bits correctly?

**Comment by pauldumais** [comment]
It just so happened that we worked on it at the same time, I was attempting to get vnc connections working to iDRAC 8 servers, which requires ZRLE as the only encoding type supported, I noticed the work done by @Ekstazi on #1283 and worked on that as a base.  I noticed that @rosmo had put in the same fix with the `allowIncomplete` so I used the same fix for that file.  I ran the #1587 PR to see if I could use it instead of my changes and it appears to be to leave some weird rendering tearing artifacts on the screen, and mine renders the screen with no artifacts.

See the attached screenshot images in comparison:

pr1589
pr1587

**Comment by pauldumais** [comment]
> Ok I understand. Thanks for testing the code from #1587 in your use case. Ideally the merged code should work well in both cases.
> 
> Despite it not being required for the code to work, I think the new encoding should be added to `core/encodings.js`.
> 
> You think you could write some unit tests for this? That's something we'd like to see before moving on.

I pushed my changes with unit tests.

**Comment by CendioOssman** [comment]
Thanks. If you squash these commits together I can go ahead and merge this.

Did you test implementing this without modifying `Inflator`? It should be possible by inflating as you go, which in some cases means just a single byte.

**Review by samhed — CHANGES_REQUESTED** [review]
One of the new ZRLE unit tests are failing it seems.

**Review by samhed — APPROVED** [review]
Looks good, thanks!

**Comment by samhed** [comment]
Do you think you could squash your changes into one commit?

**Comment by pdlan** [comment]
It seems that encodings.encodingZRLE is missing.

**Comment by CendioOssman** [comment]
Indeed. Apparently we don't have a proper test for that part. I'll have a look.

**Comment by CendioOssman** [comment]
Fixed in 65d6357cdf37f6523bf04cccadc8188f4fee462e. Thanks for noticing!

**Comment by Neustradamus** [comment]
It is linked to:
- https://github.com/novnc/noVNC/issues/25
- https://github.com/novnc/noVNC/issues/545

**Pull request merged**
