### PR TITLE
Handle empty rects from the server

### LINKED ISSUE #1436: Failed while connected: Error decoding rect: TypeError
The connection works. For a split second I can see the remote screen. Then the connection closes.

The browser log is as follows:

> User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
> display.js:69 << Display.constructor
> rfb.js:288 << RFB.constructor
> rfb.js:760 New state 'connecting', was ''.
> rfb.js:505 >> RFB.connect
> rfb.js:507 connecting to ws://192.168.15.89:6080/websockify
> rfb.js:554 << RFB.connect
> websock.js:190 >> WebSock.onopen
> rfb.js:242 Starting VNC handshake
> websock.js:196 << WebSock.onopen
> rfb.js:1220 Server ProtocolVersion: 003.003
> rfb.js:1260 Sent ProtocolVersion: 003.003
> rfb.js:1322 Authenticating using scheme: 2
> ui.js:1180 Server asked for credentials
> credentials @ ui.js:1180
> (anonymous) @ eventtarget.js:32
> dispatchEvent @ eventtarget.js:32
> _negotiateStdVNCAuth @ rfb.js:1470
> _negotiateAuthentication @ rfb.js:1621
> _initMsg @ rfb.js:1804
> _negotiateSecurity @ rfb.js:1324
> _initMsg @ rfb.js:1801
> _handleMessage @ rfb.js:856
> (anonymous) @ rfb.js:236
> _recvMessage @ websock.js:283
> rfb.js:1645 Authentication OK
> rfb.js:1719 Screen: 1024x768, bpp: 32, depth: 32, bigEndian: 0, trueColor: 1, redMax: 255, greenMax: 255, blueMax: 255, redShift: 16, greenShift: 8, blueShift: 0
> rfb.js:760 New state 'connected', was 'connecting'.
> **rfb.js:808 Failed while connected: Error decoding rect: TypeError: Failed to execute 'createImageData' on 'CanvasRenderingContext2D': Value is not of type 'long'.**
> _fail @ rfb.js:808
> _handleDataRect @ rfb.js:2473
> _handleRect @ rfb.js:2208
> _framebufferUpdate @ rfb.js:2160
> _normalMsg @ rfb.js:2076
> _handleMessage @ rfb.js:847
> (anonymous) @ rfb.js:236
> _recvMessage @ websock.js:283
> rfb.js:760 New state 'disconnecting', was 'connected'.
> rfb.js:558 >> RFB.disconnect
> keyboard.js:308 >> Keyboard.allKeysUp
> keyboard.js:312 << Keyboard.allKeysUp
> websock.js:214 Closing WebSocket connection
> rfb.js:587 << RFB.disconnect
> rfb.js:760 New state 'disconnected', was 'disconnecting'.
> rfb.js:763 Clearing disconnect timer
> **websock.js:185 WebSocket connection to 'ws://192.168.15.89:6080/websockify' failed: Received a broken close frame containing a reserved status code.**
> open @ websock.js:185
> _connect @ rfb.js:511
> _updateConnectionState @ rfb.js:773
> websock.js:204 >> WebSock.onerror: [object Event]
> rfb.js:282 WebSocket on-error event
> (anonymous) @ rfb.js:282
> _websocket.onerror @ websock.js:205
> error (async)
> open @ websock.js:203
> _connect @ rfb.js:511
> _updateConnectionState @ rfb.js:773
> setTimeout (async)
> RFB @ rfb.js:286
> connect @ ui.js:1026
> websock.js:206 << WebSock.onerror: [object Event]
> websock.js:199 >> WebSock.onclose
> websock.js:201 << WebSock.onclose

I attach a record-file.
[log.log](https://github.com/novnc/noVNC/files/4891002/log.log)

edit:
Browser version: Chrome Version 83.0.4103.116 (64-Bit)
OS Client: Windows 10 Pro 1909
noVNC Version: 1.1.0, 1.2.0-beta, and git pull 2020-07-08
VNC server name/version: unknown. It's included in the firmware of the Keyence XG-X controller
I can connect with RealVNC Viewer and UltraVNC Viewer

### PR DESCRIPTION
**Pull request by CendioOssman**
These are very pointless for the server to send, but not a violation of
the protocol so we need to be able to handle them. We've seen this
happen in real world scenarios a few times.

Fixes #1436.

### CODE REVIEW

**Comment by samhed** [comment]
Does this actually fix #1436 though? You didn't make changes to the general code path in rfb or websock, and no changes to core/decoders/raw.js?

The reason the tests for raw.js works seems to be the fact that when we pass `[]` as data, `FakeWebSocket` doesn't call the decoder:

https://github.com/novnc/noVNC/blob/3037eb16f73efc1f4c3ffc07668b5bd3b4e2c50b/tests/fake.websocket.js#L68

In #1436 the raw decoder was called but width and height was zero.

**Comment by CendioOssman** [comment]
I was a bit surprised that the test passed right away. But I figured the other cleanup of encoders fixed it. I'll have another look.

**Comment by CendioOssman** [comment]
Fixed in b91b1e8edccc978dbc94d1a22651d298d6cdb37a.

**Comment by samhed** [comment]
Nice

**Pull request merged**
