### PR TITLE
Update Dutch translation

### PR DESCRIPTION
**Pull request by yvanoers**
Updated Dutch translation

### CODE REVIEW

**Comment by samhed** [comment]
Nvm, I can fix that. We forgot to update the json file for the swedish translation as well.

**Comment by samhed** [comment]
I saw now that there are still 4 strings marked as fuzzy, but it looks like the strings were updated. I guess you edited the files by hand and just forgot to remove the fuzzy-marks?

**Comment by samhed** [comment]
One question regarding one of the fuzzy strings:

    #: ../app/ui.js:1098
    #, fuzzy
    msgid "Reconnecting..."
    msgstr "Verbinden..."

That is the same word which is used for "Connecting...", is that correct?

**Comment by samhed** [comment]
Since it would be nice to finish this now, I am going with "Opnieuw verbinding maken..." I hope that's OK.

**Comment by samhed** [comment]
Changed the "Reconnecting..." translation in 061488f8f149162072d36980923834d4d26b5ee8

**Comment by yvanoers** [comment]
I did edit the files by hand, but left the fuzzy marks in on purpose. Since I have no working noVNC setup and too little time on my hands to set one up, I couldn't really be sure the fuzzy ones are now OK. And I didn't want to make you guys wait indefinitely for me to verify the translations :)
Anyway, "Opnieuw verbinding maken..." is just fine.

**Comment by samhed** [comment]
Ok, thanks for explaining

**Pull request merged**
