### PR TITLE
flip display only if tab is visible (fixes issue #1302 memory leak on inactive tabs)

### PR DESCRIPTION
**Pull request by phcapde**

### CODE REVIEW

**Comment by CendioOssman** [comment]
Nice find. :)

So it would seem there is some bug with Chrome's `CanvasRenderingContext2D.drawImage()`. Do you think you could report it to them? Perhaps even put together a small test case? Even if we make any changes they'll have to wait for a release until they are widely deployed. So Chrome is in a much better position to fix this.

As for this PR, I think it might be possible to merge something like this. I'm not a huge fan of adding workarounds for clear (and serious) bugs in other software, but in this case it would also be a slight efficiency improvement as there is no need to update a screen that isn't visible. Two notes though:

 * `document.hidden` is deprecated. `document.visibiltyState` is the current property.

 * We need to handle the `visibilitychange` event or we might fail to show the updates once the tab becomes visible again.

**Comment by gicuuu3** [comment]
Hello! I've been looking into this issue for a while and I think that the chrome team is aware and that it should be fixed by this commit:

https://chromium-review.googlesource.com/c/chromium/src/+/1836016

Do you think that matches the current situation?

**Comment by CendioOssman** [comment]
I don't think so, unless there is something subtle going on internally in Chrome. We are copying from one canvas to another. So there is no array object directly involved.

My guess would be that Chrome adds a queue of things to draw. But they've stopped processing that queue for hidden tabs, so it keeps growing.

**Comment by gicuuu3** [comment]
I see. That commit was prompted as a bug fix to another memory leak in their `FileReader` API. I thought it might be connected somehow.

I wonder if they're slowly giving more attention to their `OffscreenCanvas` API and did not notice potential issues with the classical background canvas approach.

Regardless, thanks a lot for your input!

**Comment by Philippe-Capdepuy** [comment]
Yes I guess it is an optimization anyway. For the visibilityState, I'm no expert but as long as the property is correctly updated by the browser I guess we don't really need to catch the event as the next drawing call (which seem to happen more or less constantly) should perform the flip.

I'm afraid I won't have time to report back in chrome, in just really needed it to work properly for my use case ;)

**Comment by CendioOssman** [comment]
The redraws only happen if we're getting updates from the server, which we cannot rely on for all scenarios. So I'm afraid we'll need an event handler or we'll start getting bug reports about the screen not updating properly. :)

**Comment by juanjoDiaz** [comment]
Instead of stop doing the flip conditionally, wouldn't it be possible to stop requesting updates from the server?

At glance, something like modifying the `RfB._onFlush` like:
```js
    _onFlush() {
        this._flushing = false;

         if (this.displayIsVisible) {
             // Resume processing
             if (this._sock.rQlen > 0) {
                 this._handle_message();
             }
          }
    }
```
and have an event listener like:
```js
document.addEventListener("visibilitychange", function() {
  if (document.visibilityState === 'visible') {
    this.displayIsVisible = true;
    this.onFlush(); // To resume processing
  } else {
    this.displayIsVisible = false;
  }
});
```

I'm not an expert in the RFB protocol so I'm not sure if what I'm saying is total nonsense.
What do you guys think?


I've been wondering if it would be possible to do something like this using the IntersectionObserver API so I can have a page with many canvases but only the visible ones are actually consuming resources.

**Comment by CendioOssman** [comment]
For a modern server we don't actively request things, so we have to tell the server to pause. It's definitely possible, but it will require a bit of work.

But that's probably step two. We can start with finishing up this part.

**Pull request closed without merging**
