### PR TITLE
Make the screen background customizable

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Add a pubic accessor to the screen style -> background property, so it can be customised from the client code if needed.

The previous discussion can be found at https://github.com/novnc/noVNC/pull/1189

### CODE REVIEW

**Comment by CendioOssman** [comment]
Looks mostly okay to me. I'd just like to see some tweaks of the terms. We've tried to avoid referring to the screen or canvas in the documentation, and instead present the RFB object as self contained.

So perhaps just call it `background`? And document it as setting the [background](https://developer.mozilla.org/en-US/docs/Web/CSS/background) CSS style for the area not covered by the remote session.

**Comment by mykola-mokhnach** [comment]
@CendioOssman Sure, will do

**Comment by CendioOssman** [comment]
The link got the tags backwards, so it didn't parse correctly. :)

Almost there. Perhaps bike shedding, but I'd really like to avoid mentioning the canvas. The rest of the document refers to the displayed image as the remote session.  So less details about how this is technically implemented and more the visible end result. We don't want people assuming a specific internal architecture as we might change that.

**Comment by mykola-mokhnach** [comment]
Updated the docstring

**Comment by CendioOssman** [comment]
Thanks. Looks good to me as well. Could you merge all the commits in to one and force update this PR?

**Comment by mykola-mokhnach** [comment]
Yes, will do. BTW you could also squash on merge. Github does provide such functionality automatically

**Comment by samhed** [comment]
> BTW you could also squash on merge. Github does provide such functionality automatically

There's one small difference if we do this - we won't get the merge commit.

**Pull request merged**
