### PR TITLE
Update translation po/template strings

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Current pot & po files are all dated, let's update them!

### CODE REVIEW

**Comment by CendioOssman** [comment]
The plan is to update these things for release, not randomly during development. It would make a very noisy history otherwise.

So thank you for keeping an eye on things, but I'm afraid we won't be merging this.

**Comment by PeterDaveHello** [comment]
@CendioOssman can we have it more flexible here? The problem is that I translated from the old template which is annoying ... and I don't think very translator will notice it, know how to deal with it.

**Comment by CendioOssman** [comment]
Right, but I don't think we necessarily want people translating from `master` as it is a moving target. Right now is a bit special since we've never made a release with translations, so hopefully it will be more sane once we get things rolling properly.

**Comment by PeterDaveHello** [comment]
Got it, if you can accept, maybe just update the `pot`? If not, never mind.

**Comment by PeterDaveHello** [comment]
Just that you know that I translated the project(#966), and then, I found that I was translating from an old template, so I needed to update the template and translate the new strings, drop the translation for the dropped strings, I think it waste time a little bit.

**Comment by CendioOssman** [comment]
The plane is to start the release work next week, so that will mean an updated `.pot` file by then.

**Pull request closed without merging**
