### PR TITLE
Set up for Publishing on NPM

### LINKED ISSUE #675: We should publish on NPM
As a follow-up to #496, we should set up Travis to automatically publish to NPM on a successful tagged version.

### LINKED ISSUE #797: Set up builds for production and auto-publish on tags using Travis
We should auto-publish production builds of noVNC for the supported "build" types, and publish the CommonJS version to NPM.  This should be done automatically using Travis when we tag a release.

### PR DESCRIPTION
**Pull request by DirectXMan12**
This sets us up for publishing on NPM under the @novnc/novnc repository.
The publishing is automated via Travis whenever we add a new tag to the repo.

This also sets us at the v1.0.0-testing.2 release, which we can use to test uploading to NPM.

Closes #797 
Closes #675

### CODE REVIEW

**Comment by DirectXMan12** [comment]
@kanaka I've added you to the @novnc organization on NPM. @samhed @CendioOssman if you send me your NPM user names, I'll add you as well.

**Comment by DirectXMan12** [comment]
ok, I'm going to test out publishing

**Comment by DirectXMan12** [comment]
🎉 it works!  Check out https://www.npmjs.com/package/@novnc/novnc!

I plan on unpublishing the testing releases within 24h to make way for a proper release (technically, `testing > beta > alpha`, unfortunately).

@samhed @CendioOssman this look fine to you?

**Comment by DirectXMan12** [comment]
Also, note the nifty build stages -- we only publish if all tests run succesfully.

**Comment by DirectXMan12** [comment]
Once this merges, we just need to actually figure out what goes in the release notes! 📝

**Comment by kanaka** [comment]
:thumbsup: Great work! I'm hopeful this will really pay off long term.

**Comment by CendioOssman** [comment]
> @samhed @CendioOssman if you send me your NPM user names, I'll add you as well.

I've created the account `cendioossman` on npm now.

> @samhed @CendioOssman this look fine to you?

I'm unfortunately not too familiar with the details of NPM, but it looks fine except for the addition of the file `package-lock.json`. Was that a mistake? 
Have you done a test run as a user of this new module?

Can we modify the info shown at npmjs.com? It currently shows stuff relevant for the app, not the library.

Not sure if we have a better forum for this, but I'd also like to suggest moving the API documentation from the wiki to the repo before release so that it is properly associated with the correct version.

**Comment by DirectXMan12** [comment]
package-lock.json is intentional.  It's supposed to be checked in to the repo, but will never be published, according to the docs (https://docs.npmjs.com/files/package-lock.json)

**Comment by DirectXMan12** [comment]
> Can we modify the info shown at npmjs.com

I believe that's just whatever is in the readme file, unless you manually set a field, but I believe that may be more complicated than it looks.  Let's follow up on that in a further PR before release.

**Comment by DirectXMan12** [comment]
> Have you done a test run as a user of this new module?

Yep, I tried running rollup on the raw files, and browserify with some copied-over app files on the `lib/` files.

**Comment by DirectXMan12** [comment]
Ok, since I have LGTMs, I'm going to merge.  We can follow up with additional enhancements to documentation or README files before release.

**Comment by CendioOssman** [comment]
> package-lock.json is intentional. It's supposed to be checked in to the repo, but will never be published, according to the docs (https://docs.npmjs.com/files/package-lock.json)

That still seems like a very bad idea. It means we will never get any bug fixes or improvements to any of our dependencies. I'm afraid that's a :-1: for me.

**Comment by samhed** [comment]
I feel like we shouldn't lock versions of our dependencies. I think that an active development project like noVNC would benefit more from using updated packages. It seems the docs talk about structured deployment scenarios. I trust that companies and products that use noVNC have their own testing and roll outs.

**Comment by DirectXMan12** [comment]
ack, we can remove it if you want

**Comment by CendioOssman** [comment]
Alright. Removed in 1150497123f0a73b84d4af82991efeee6fc11961.

**Comment by pmcochrane** [comment]
For info I have used the npm package to install novnc to my meteor app. It is working correctly although it's giving a message upon install. Don't know if this is deliberate or not on your part.

npm install @novnc/novnc
npm WARN deprecated @novnc/novnc@1.0.0-testing.2: this was a version for testing the release process

**Pull request merged**
