### PR TITLE
Properly give focus to canvas

### PR DESCRIPTION
**Pull request by CendioOssman**
Possible fix for #914, #915 and #692. Needs testing.

### CODE REVIEW

**Comment by CendioOssman** [comment]
Need to check how it works on mobile devices where that extra input field is used as well.

**Comment by CendioOssman** [comment]
Works well with Chrome and Firefox on Pixel C with on screen keyboard. Physical keyboard has some quirks though:

 a) Touching the canvas doesn't move focus there (need to add a `touchbegin` listener)
 b) It's not readily apparent that the focus is on input elements

**Comment by samhed** [comment]
Running this makes IE and Edge work well! Can verify that it fixes #692.

One should also note that this PR brings a change in behavior for users. If the user clicks in the settings and then proceeds to type with the keyboard, the input will no longer be sent to the server. The user has to change focus by clicking on the canvas first.

**Comment by samhed** [comment]
You have only seen issues with a physical keyboard on android so far right?

**Comment by CendioOssman** [comment]
Yup. But there's also more testing to be done.

I also realised it changed the behaviour of the "touch" input field in that we'll no longer listen to key events on that. IOW it becomes the normal path rather than a fallback.

**Comment by CendioOssman** [comment]
Works well on all browsers and platforms now. Even tested physical keyboard on Android and iOS.

**Comment by samhed** [comment]
nice!

**Pull request merged**
