### PR TITLE
Add version number to UI

### PR DESCRIPTION
**Pull request by juanjoDiaz**
A very simple solution to #1222 that looks like the suggestion in the issue

### CODE REVIEW

**Comment by samhed** [comment]
noVNC_version

It looks decent, but I'd rather want something more hidden. Either if we hide it when connected, or put it in the settings somewhere. What do you think?

**Comment by juanjoDiaz** [comment]
I've submitted an alternative proposal.

Btw, why do your sidebar has so many icons? Mine only has "Fullscreen" and "Settings".

**Comment by samhed** [comment]
> Btw, why do your sidebar has so many icons? Mine only has "Fullscreen" and "Settings".

I'm connected.

**Comment by samhed** [comment]
Closing in favor of #1265

**Pull request closed without merging**
