### PR TITLE
Fix iOS 9 compatibility

### LINKED ISSUE #815: module loader doesn't work on Safari 9
We have an old iPad here that's still on iOS 9.3.5. The module loader fails to work here with this error:

```
[Error] SyntaxError: Strict mode does not allow function declarations in a lexically nested statement.
	(anonymous function) (browser-es-module-loader.js:1172)
```

### PR DESCRIPTION
**Pull request by CendioOssman**
Fixes #815.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
feel free to merge once tests pass (I restarted the job).

**Comment by DirectXMan12** [comment]
something's borked with Travis.  Will investigate.

**Comment by DirectXMan12** [comment]
can you rebase just to make sure you have the latest Travis changes?

**Comment by CendioOssman** [comment]
The merge will sort that out. And the branch went through travis from my tree here:

https://travis-ci.org/CendioOssman/noVNC/builds/238755714?utm_source=github_status&utm_medium=notification

**Pull request merged**
