### PR TITLE
QEMU Extended Audio Support

### PR DESCRIPTION
**Pull request by tinyzimmer**
I opened a fresh draft because I had way too many mistakes on my first branch :stuck_out_tongue: 

I have not yet tested these changes and obviously documentation will need to be updated. This is mainly intended to continue the discussion from #302.

Forgive me if I made some mistakes, since this is my first time really digging into the underlying protocol, but this is my first draft attempt at implementing handling for the [QEMU Audio Server Message](https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#qemu-audio-server-message) and public methods wrapping the [QEMU Audio Client Message](https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#qemu-audio-client-message).

I'm trying to figure out the best way I could go about testing these changes and fine tuning them. In my current project where I'm using noVNC I am simply proxying the data from an Xvnc server, so I would need to find a good one to use that supports the extended protocol.

### CODE REVIEW

**Comment by tinyzimmer** [comment]
For starters, one thing that I know will need to be changed here is how the audio is being played. I assume it's raw PCM data coming over the socket. And I am not sure if the `MediaSource` API can handle that, but I believe `window.AudioContext` can.

**Comment by alectrocute** [comment]
Hey all. For what it's worth, another OSS project called Neko managed to implement `pulseaudio` playback elegantly. May be worth checking out how they play back audio (which I assume is PCM?): https://github.com/nurdism/neko/search?q=pulseaudio&unscoped_q=pulseaudio

**Comment by tinyzimmer** [comment]
> Hey all. For what it's worth, another OSS project called Neko managed to implement `pulseaudio` playback elegantly. May be worth checking out how they play back audio (which I assume is PCM?): https://github.com/nurdism/neko/search?q=pulseaudio&unscoped_q=pulseaudio

That actually looks interesting. I'm surprised I didn't come across it when I was working on my side project which is very similar. I'll poke through the code later, but on the README they mention that it uses WebRTC. If that is the case for the audio as well, I am not sure if it would be a good example for implementing here. 

WebRTC is definitely the easiest way to do something like this, but there are infrastructure requirements that I don't think would be available in most use cases.

**Comment by samhed** [comment]
Thanks for the PR!

Regarding a server for testing - from what I can gather it seems only the built in VNC server in libvirt/QEMU supports this.

**Comment by tinyzimmer** [comment]
Yea that's what I gathered too from searching about. So in the context of the project where I am using noVNC, I was either going to try to figure out a way to "proxy" the protocol and inject audio messages...or just spin up some qemu VMs at some point and start tinkering. I spent like an hour trying to conceptualize the former and at the time just said "nah" :stuck_out_tongue: :.

**Comment by tinyzimmer** [comment]
Just chiming in that I haven't completely forgotten about this. I may try out some testing in the coming weeks.

**Comment by samhed** [comment]
Good to hear @tinyzimmer

**Comment by jgforbes** [comment]
@tinyzimmer: Any progress on getting qemu sound channel to work with noVNC? Anything I can do to help?

**Comment by tinyzimmer** [comment]
@jgforbes I've been all over the place between starting new jobs and personal crises so I haven't had a chance to play with it extensively yet. If you want to jump it at any point by all means, but I promise I will try to get back to this *eventually*.  Some considerations I've already encountered.

The code in it's current state will not work I know that. Not without either refactoring the client to take raw PCM (lots of data), or implementing a server that can encode the audio to webm. If it's just the raw QEMU support we want to consider including anyway, then the code in this PR that calls the browser Audio APIs needs to be refactored accordingly, but the protocol stuff should be okay so far. 

Then it's just a matter of testing. Which basically using `qemu` is the only option it seems. I started down a path of implementing a sorta `libvncserver` in `go` just for kicks, but also thinking it could eventually be another option out in the wild for having a server that supports audio. That project is **very** far from completion though lol.

**Comment by jeffforbes** [comment]
@tinyzimmer Would it be possible to contact you about your QEMU VNC audio channel work outside of github?

**Comment by tinyzimmer** [comment]
Sure via slack or something like that?

**Comment by jgforbes** [comment]
I made the slack channel #vm-viewers.I am not a slack user so I will have to see how this works.I assume that github removes email address from this type of messaging.Jeffrey Forbes


-------- Original Message --------
Subject: Re: [novnc/noVNC] QEMU Extended Audio Support (#1457)

**Comment by jeffforbes** [comment]
@tinyzimmer Did you receive the email I sent to the address in your profile?

**Comment by tinyzimmer** [comment]
@jeffforbes I must have missed it, sorry. That is the correct address though. In all fairness, I haven't had time, and not sure when or if I will, to continue work on this PR in the near future 😢

**Comment by tinyzimmer** [comment]
I'm tempted to close this PR. If anything because if I do approach it again I'd like to do so from a fresh slate.

But also I am getting to the point in my project where I am adding support for QEMU machines on the server side. When I then wanted a dynamic display resolution, it made more sense to try to use Spice for those instances then to continue with noVNC. Though I think I'll try to keep support for both.

If and when I do have that finished, I'll actually have a decent test environment for if I **do** want to play with this again. And, at least for me, it'll make more sense to pick it back up then.

**Comment by samhed** [comment]
Understandable. Note however that noVNC does have support for dynamic display resolution using the ExtendedDesktopSize pseudo-encoding. I don't know if QEMU's VNC server has support for that though.

**Comment by tinyzimmer** [comment]
I am actually using that already for the current functionality I have that doesn't use QEMU. 

But to my understanding, I don't think the QEMU VNC server supports it. I think that's where they push you towards SPICE instead.

**Comment by tinyzimmer** [comment]
Yea I am noticing that as I try to integrate it. Will see where this journey takes me.

**Comment by Neustradamus** [comment]
It replaces:
- https://github.com/novnc/noVNC/pull/1456

**Comment by Neustradamus** [comment]
This PR: https://github.com/novnc/noVNC/pull/1952 replaces:
- https://github.com/novnc/noVNC/pull/1456
- https://github.com/novnc/noVNC/pull/1457
- https://github.com/novnc/noVNC/pull/1951

Linked to:
- https://github.com/novnc/noVNC/issues/302

**Pull request closed without merging**
