### PR TITLE
expose websockify's --file-only option to disable dir listing

### PR DESCRIPTION
**Pull request by msays2000**
expose --file-only option to disable dir listing

novnc_proxy optionally passes the flag to WEBSOCKIFY to disable dir listing

https://github.com/novnc/websockify/pull/536

### CODE REVIEW

**Comment by msays2000** [comment]
@CendioOssman please review this change which exposes the websockify's flag introduced via https://github.com/novnc/websockify/pull/536 to novnc_proxy

**Comment by msays2000** [comment]
@CendioOssman please review

**Comment by samhed** [comment]
At some point, we want to draw a line where stop adding new options to `novnc_proxy`. It's supposed to be a quick shortcut to get things going. We don't want it to become too complex.

**Comment by msays2000** [comment]
@CendioOssman @samhed please consider this flag, it's an optional flag (will not break existing customers) and addresses a security concern, it will be very helpful to not build wrappers around this helpful utility or skip this utility.

**Comment by CendioOssman** [comment]
Or we stop trying to get in the way of websockify and pass along any arguments we don't recognize.

I think adding this new flag is okay until then.

**Comment by msays2000** [comment]
@CendioOssman I believe websockify doesn't allow parent folder navigation out of the --web directory. So I think with --no-parent and --file-only is more secure than current.

**Comment by msays2000** [comment]
> Or we stop trying to get in the way of websockify and pass along any arguments we don't recognize.
> 
> I think adding this new flag is okay until then.

agreed, we should pass all args to websockify and let this not be the args parser but a shim caller

**Comment by msays2000** [comment]
could we please merge this and then make a change in next flag expose event to pass all args to websockify.

**Comment by msays2000** [comment]
@CendioOssman @samhed please give your blessing to merge this PR

**Comment by msays2000** [comment]
@CendioOssman folks are you interested in merging this or should I make a change to pass all args to websokify...

**Comment by CendioOssman** [comment]
It's on the todo to merge this. Unfortunately swamped with other things at the moment.

**Comment by msays2000** [comment]
@samhed @CendioOssman gentle reminder for this tiny change

**Comment by msays2000** [comment]
@samhed @CendioOssman please merge this 3 lines of change

**Pull request merged**
